[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=debug
pidfile=/var/run/supervisord.pid
minfds=1024
minprocs=200
environment=NODE_ENV=production,DEBUG=*,TZ=utc

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
stdout_events_enabled=false
stderr_events_enabled=false

[program:node]
command=node /app/api_node/src/server.js
directory=/app/api_node
autorestart=true
stdout_logfile=/var/log/node.out.log
stderr_logfile=/var/log/node.err.log
stdout_events_enabled=true
stderr_events_enabled=true

[program:postgres]
user=postgres
command=postgres -D /var/lib/postgresql/data
autorestart=true