name: bolsa_app
description: App Flutter para listar usuários e ações (projeto exemplo)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  # http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
